export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const UPDATE_CUSTOM_INCREMENT = 'UPDATE_CUSTOM_INCREMENT';
export const DISPLAY_INCREMENT_INPUT_ERROR = 'DISPLAY_INCREMENT_INPUT_ERROR';
export const ERASE_INCREMENT_INPUT_ERROR = 'ERASE_INCREMENT_INPUT_ERROR';
export const UPDATE_RANDOM_FETCH = 'UPDATE_RANDOM_FETCH';